config/routes.rb
SquadXML::Application.routes.draw do
  match '/squads/404.paa' => 'squads#logo'
  resources :squads
  resources :squad_members

  root :to => "application#index"

  devise_for :users
  devise_scope :user do
    match "/login" => "devise/sessions#new"
    match "/logout" => "devise/sessions#destroy"
    match "/signup" => "devise/registrations#new"
  end
end

app/models/squad.rb
class Squad < ActiveRecord::Base
  belongs_to :user
  has_many :squad_members

  attr_accessible :email, :name, :picture, :tag, :title, :website

  validates :name, :tag, :title, :presence => true
  validates :tag, :format => { :with => /^[A-z0-9]+$/, :message => "Only letters and numbers allowed" }
end

app/models/squad_member.rb
class SquadMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :squad

  attr_accessible :email, :icq, :name, :nickname, :remark, :uid

  validates :uid, :name, :nickname, :presence => true
  validates_numericality_of :uid
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :squad
  has_one :squad_member
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def index
    render 'static/index'
  end
end

app/controllers/squad_members_controller.rb
class SquadMembersController < ApplicationController

  before_filter :authenticate_user!

  def show
    @squad_member = SquadMember.find(params[:id])

    if current_user == @squad_member.user || current_user.admin?
      respond_to do |format|
        format.html # show.html.erb
      end
    end
  end

  def new
    @squad_member = SquadMember.new

    if current_user.squad_member
      redirect_to root_path
    else
      respond_to do |format|
        format.html # new.html.erb
      end
    end
  end

  def edit
    @squad_member = SquadMember.find(params[:id])

    if current_user == @squad_member.user || current_user.admin?
      respond_to do |format|
        format.html
      end
    end
  end

  def create
    @squad_member = SquadMember.new(params[:squad_member])
    @squad_member.squad = Squad.first # Lock to 404
    @squad_member.user = current_user

    respond_to do |format|
      if @squad_member.save
        format.html { redirect_to root_path, :notice => 'Squad member was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @squad_member = SquadMember.find(params[:id])
    @squad_member.squad = Squad.first # Lock to 404

    if current_user == @squad_member.user || current_user.admin?
      respond_to do |format|
        if @squad_member.update_attributes(params[:squad_member])
          format.html { redirect_to root_path, :notice => 'Squad member was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end
  end

  def destroy
    @squad_member = SquadMember.find(params[:id])
    if current_user == @squad_member.user || current_user.admin?
      @squad_member.destroy

      respond_to do |format|
        format.html { redirect_to squad_members_url }
      end
    end
  end
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :logo]
  before_filter do
    if params[:action] != 'show' && params[:action] != 'logo'
      redirect_to login_path unless current_user && current_user.admin?
    end
  end

  def logo
    send_file 'public/squad/404.paa', :type => "application/octet-stream", :x_sendfile => true
  end

  def index
    if current_user.squad
      redirect_to squad_path(current_user.squad)
    else
      redirect_to new_squad_path
    end
  end

  def show
    @squad = Squad.find(params[:id])

    respond_to do |format|
      if current_user
        format.html # show.html.erb
      end
      format.xml { render :layout => false }
    end
  end

  def new
    @squad = Squad.new

    if current_user.admin?
      respond_to do |format|
        format.html # new.html.erb
      end
    end
  end

  def edit
    @squad = Squad.find(params[:id])

    if current_user == @squad.user || current_user.admin?
      respond_to do |format|
        format.html
      end
    end
  end

  def create
    @squad = Squad.new(params[:squad])
    @squad.user = current_user

    if current_user.admin?
      respond_to do |format|
        if @squad.save
          format.html { redirect_to @squad, notice: 'Squad was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end
  end

  def update
    @squad = Squad.find(params[:id])

    if current_user == @squad.user || current_user.admin?
      respond_to do |format|
        if @squad.update_attributes(params[:squad])
          format.html { redirect_to @squad, notice: 'Squad was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end
  end

  def destroy
    @squad = Squad.find(params[:id])
    if current_user == @squad.user || current_user.admin?
      @squad.destroy

      respond_to do |format|
        format.html { redirect_to squads_url }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/squad_members_helper.rb
module SquadMembersHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title SquadXML by Wakeuphate
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag :modernizr
    = csrf_meta_tags
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'SquadXML by Wakeuphate', root_path, :class => 'brand'
          .nav-collapse.collapse
            %ul.nav
              %li
                - if current_user.admin?
                  - if current_user.squad
                    = link_to "Manage Squad: #{current_user.squad.tag}", squad_path(current_user.squad)
              %li
                - if current_user.squad_member
                  = link_to "Update My Info", squad_member_path(current_user.squad_member)
                - else
                  = link_to "Create My Squad Member", new_squad_member_path
          / /.nav-collapse
    .container
      - if notice
        .alert.alert-success
          = notice
      - if alert
        .alert.alert-error
          %strong Warning!
          = alert
      = yield
    / /container
    = javascript_include_tag "application"

app/views/layouts/simple.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title SquadXML by Wakeuphate
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag "simple", :media => "all"
    = csrf_meta_tags
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  %body
    .container
      - if notice
        .alert.alert-success
          %strong Notice!
          = notice
      - if alert
        .alert.alert-error
          %strong Warning!
          = alert
      = yield
    / /container
    = javascript_include_tag "application"

app/views/squad_members/_form.html.haml
= simple_form_for(@squad_member) do |f|
  = f.error_notification

  .form-inputs
    = f.input :uid
    = f.input :nickname
    = f.input :name
    = f.input :email
    = f.input :icq, :as => :hidden
    = f.input :remark

  .form-actions
    = f.button :submit

app/views/squad_members/edit.html.haml
%h1 Editing #{@squad_member.nickname}

= render 'form'

= link_to 'Show', @squad_member
\|
= link_to 'Back', squad_members_path

app/views/squad_members/new.html.haml
%h1 New Squad Member

= render 'form'

= link_to 'Back', squad_members_path

app/views/squad_members/show.html.haml
%p#notice= notice

%p
  %b Squad:
  = @squad_member.squad.name
%p
  %b Uid:
  = @squad_member.uid
%p
  %b Nickname:
  = @squad_member.nickname
%p
  %b Name:
  = @squad_member.name
%p
  %b Email:
  = @squad_member.email
%p
  %b Remark:
  = @squad_member.remark

= link_to 'Edit', edit_squad_member_path(@squad_member)
\|
= link_to 'Back', squad_members_path

app/views/squads/_form.html.haml
= simple_form_for(@squad) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :tag
    = f.input :email
    = f.input :website
    = f.input :picture
    = f.input :title

  .form-actions
    = f.button :submit

app/views/squads/edit.html.haml
%h1 Editing #{@squad.name}

= render 'form'

= link_to 'Show', @squad
\|
= link_to 'Back', squads_path

app/views/squads/new.html.haml
%h1 New squad

= render 'form'

= link_to 'Back', squads_path

app/views/squads/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @squad.name
%p
  %b Tag:
  = @squad.tag
%p
  %b Email:
  = @squad.email
%p
  %b Website:
  = @squad.website
%p
  %b Picture:
  = @squad.picture
%p
  %b Title:
  = @squad.title

- if current_user.admin?
  = link_to 'Edit', edit_squad_path(@squad)

  %hr/
  %h2 Squad Members:
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th Uid
      %th Nickname
      %th Name
      %th Email
      %th Remark
      %th
      %th
      %th

    - @squad.squad_members.each do |squad_member|
      %tr
        %td= squad_member.uid
        %td= squad_member.nickname
        %td= squad_member.name
        %td= squad_member.email
        %td= squad_member.remark
        %td= link_to 'Show', squad_member
        %td= link_to 'Edit', edit_squad_member_path(squad_member)
        %td= link_to 'Destroy', squad_member, :method => :delete, :data => { :confirm => 'Are you sure?' }